# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      POSTGRE_DATABASE_URL: ${{ secrets.POSTGRE_DATABASE_URL }}
      MONGO_DATABASE_URL: ${{ secrets.MONGO_DATABASE_URL }}
      MONGO_DATABASE_NAME: ${{ secrets.MONGO_DATABASE_NAME }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Create .env file for dotenv
      run: |
          echo "POSTGRE_DATABASE_URL=${{ secrets.POSTGRE_DATABASE_URL }}" >> .env
          echo "MONGO_DATABASE_URL=${{ secrets.MONGO_DATABASE_URL }}" >> .env
          echo "MONGO_DATABASE_NAME=${{ secrets.MONGO_DATABASE_NAME }}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          
    - run: npm ci
      working-directory: ./backend
    - run: npm run build --if-present
      working-directory: ./backend
    - run: npm test
      working-directory: ./backend
